# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy source Content
COPY ./NotificationService/src ./NotificationService/src

# Copy Shared Content
COPY ./Shared ./Shared

# Restore Dependencies
RUN dotnet restore "NotificationService/src/NotificationService.API/NotificationService.API.csproj"

# Publishes API
RUN dotnet publish "NotificationService/src/NotificationService.API/NotificationService.API.csproj" -c Release -o out

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out ./

EXPOSE 8080
ENTRYPOINT ["dotnet", "NotificationService.API.dll"]