name: rabbitmq
services:
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RabbitMqSettings__User}
      RABBITMQ_DEFAULT_PASS: ${RabbitMqSettings__Password}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - complyapi-network
      
volumes:
  rabbitmq_data:

networks:
  complyapi-network:
    external: true