# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy source Content
COPY ./PaymentService/src ./PaymentService/src

# Copy Shared Content
COPY ./Shared ./Shared

# Restore Dependencies
RUN dotnet restore "PaymentService/src/PaymentService.Api/PaymentService.Api.csproj"

# Publishes API
RUN dotnet publish "PaymentService/src/PaymentService.Api/PaymentService.Api.csproj" -c Release -o out

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out ./

EXPOSE 8080
ENTRYPOINT ["dotnet", "PaymentService.Api.dll"]