name: apigateway
services:
  nginx:
    image: nginx:stable-alpine
    container_name: complyapi-gateway
    restart: unless-stopped
    ports:
      - "9191:8080"
    volumes:
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - complyapi-network

networks:
  complyapi-network:
    external: true