# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy source Content
COPY ./ListingService/src ./ListingService/src

# Copy Shared Content
COPY ./Shared ./Shared

# Restore Dependencies
RUN dotnet restore "ListingService/src/ListingService.Api/ListingService.Api.csproj"

# Publishes API
RUN dotnet publish "ListingService/src/ListingService.Api/ListingService.Api.csproj" -c Release -o out

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out ./

EXPOSE 8080
ENTRYPOINT ["dotnet", "ListingService.Api.dll"]