# 1. Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy source Content
COPY ./ProductService/src ./ProductService/src

# Copy Shared Content
COPY ./Shared ./Shared

# Restore Dependencies
RUN dotnet restore "ProductService/src/ProductService.API/ProductService.API.csproj"

# Publishes API
RUN dotnet publish "ProductService/src/ProductService.API/ProductService.API.csproj" -c Release -o out

# 2. Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out ./

EXPOSE 8080
ENTRYPOINT ["dotnet", "ProductService.API.dll"]