# Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Copy source Content
COPY ./UserService/src ./UserService/src

# Copy Shared Content
COPY ./Shared ./Shared

# Restore Dependencies
RUN dotnet restore "UserService/src/UserService.api/UserService.Api.csproj"

# Publishes API
RUN dotnet publish "UserService/src/UserService.api/UserService.Api.csproj" -c Release -o out

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/out ./

EXPOSE 8080
ENTRYPOINT ["dotnet", "UserService.Api.dll"]